spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.webboard.util
  configuration:
    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
