spring:
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.webboard.util
  configuration:
    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
