spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    sql-script-encoding: UTF-8  # data.sql 한글깨짐 해결
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  main:
#    allow-bean-definition-overriding: true

server:
  port: 9898
