spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    sql-script-encoding: UTF-8  # data.sql 한글깨짐 해결
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml


server:
  port: 9898
