INSERT INTO ROLE (ROLE_NO, ROLE) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_NO, ROLE) VALUES (2, 'USER');

INSERT INTO USER (USER_NO, USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES (1, 'admin', '$2a$10$FgKkqKMRPttp6AjAMlJCUe5K0PFlynb90.22TlKAV9KeG72cG1TsK', '나관리', '관리자');
INSERT INTO USER (USER_NO, USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES (2, 'user1', '$2a$10$Y5n6VrvcfeuijzgDZKW6Ve41wJnGL/F/C5QNmlKv7pPOlUjZYtahK', '홍길동', '나작성');
INSERT INTO USER (USER_NO, USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES (3, 'user2', '$2a$10$fO6F5gFhU7eQwR3vGgemseh/Lh9OTk8/./rKkmNnWdb6u56PgMk7.', '성춘향', '오작성');

INSERT INTO USER_ROLE (ROLE_NO, USER_NO) VALUES (1, 1);
INSERT INTO USER_ROLE (ROLE_NO, USER_NO) VALUES (2, 1);
INSERT INTO USER_ROLE (ROLE_NO, USER_NO) VALUES (2, 2);
INSERT INTO USER_ROLE (ROLE_NO, USER_NO) VALUES (2, 3);

INSERT INTO BOARD (NAME) VALUES ('일반게시판');
INSERT INTO BOARD (NAME) VALUES ('이벤트게시판');

INSERT INTO POST (BOARD_NO, USER_ID, NICKNAME, TITLE, CONTENT, CREATE_DT, UPDATE_DT) VALUES (1, 'user1', '나작성', '제목', '내용', NOW(), NOW());
INSERT INTO POST (BOARD_NO, USER_ID, NICKNAME, TITLE, CONTENT, CREATE_DT, UPDATE_DT) VALUES (1, 'user2', '오작성', '제목2', '내용2', NOW(), NOW());
INSERT INTO POST (BOARD_NO, USER_ID, NICKNAME, TITLE, CONTENT, CREATE_DT, UPDATE_DT) VALUES (2, 'admin', '관리자', '이벤트', '<script>
    alert("a")
</script>', NOW(), NOW());
