DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_ROLE;

CREATE TABLE BOARD (
      BOARD_NO BIGINT PRIMARY KEY AUTO_INCREMENT
    , NAME VARCHAR2(255) NOT NULL
);
CREATE TABLE POST (
      POST_NO BIGINT PRIMARY KEY AUTO_INCREMENT
    , BOARD_NO BIGINT NOT NULL
    , USER_ID VARCHAR2(255) NOT NULL
    , NICKNAME VARCHAR2(255) NOT NULL
    , TITLE VARCHAR2(500) NOT NULL
    , CONTENT VARCHAR2(4000) NOT NULL
    , CREATE_DT DATETIME
    , UPDATE_DT DATETIME
);
CREATE TABLE USER (
      USER_NO BIGINT PRIMARY KEY AUTO_INCREMENT
    , USER_ID VARCHAR2(255) NOT NULL
    , PASSWORD VARCHAR2(255) NOT NULL
    , USER_NAME  VARCHAR2(255) NOT NULL
    , NICKNAME  VARCHAR2(255) NOT NULL
);
CREATE TABLE ROLE (
      ROLE_NO BIGINT PRIMARY KEY AUTO_INCREMENT
    , ROLE VARCHAR2(255)
);
CREATE TABLE USER_ROLE (
      USER_NO BIGINT NOT NULL
    , ROLE_NO BIGINT NOT NULL
);